### ISSUE TITLE
General Disscusion

### ISSUE THREAD

**Issue by CosmicWebServices** [bridgevar/Bridge-Var#1]

**Comment by CosmicWebServices** [comment]
So what are we going to do with the server?

**Comment by ghost** [comment]
I could also make a nodeJS version if you want (I'm not really a python person).

**Comment by ghost** [comment]
Strange picture in my head:  half person, half snake...

**Comment by CosmicWebServices** [comment]
lol and I am a more python person but a quick learner... and I see how that can be way better so lets do it!

**Comment by CosmicWebServices** [comment]
You have access to make respetorys as far as I know

**Comment by CosmicWebServices** [comment]
but I can make it

**Comment by CosmicWebServices** [comment]
if u want

**Comment by ghost** [comment]
Ok.  I think there is a better way to do this then using a `send` variable.

**Comment by CosmicWebServices** [comment]
With node.js or python

**Comment by CosmicWebServices** [comment]
Oh now I know what you are talking about

**Comment by CosmicWebServices** [comment]
I did that because people may not want to send new info all the time and it give the server a rest

**Comment by CosmicWebServices** [comment]
If u have a better idea make a pr

**Comment by CosmicWebServices** [comment]
@joker314 do u want to join?

**Comment by ghost** [comment]
The the nodejs api module has a onchange event that doesn't just keep polling the cloud server for changes.  It uses the socket version of the api that directly sends the changes straight to the client.

**Comment by CosmicWebServices** [comment]
You can also do that in python

**Comment by ghost** [comment]
Well maybe we should use that...

**Comment by CosmicWebServices** [comment]
OK I will make a branch

**Comment by CosmicWebServices** [comment]
it is on change

**Comment by CosmicWebServices** [comment]
there are many ways to do it I want a simple way

**Comment by CosmicWebServices** [comment]
I mean small amount of code way

**Comment by ghost** [comment]
I'm working on the node version;  Look how easy the script that prints out every change to a variable in [scratch-api on npm](https://www.npmjs.com/package/scratch-api)

**Comment by ghost** [comment]
It is just
`var Scratch = require('scratch-api');
Scratch.UserSession.load(function(err, user) {
  user.cloudSession(<project>, function(err, cloud) {
    cloud.on('set', function(name, value) {
      console.log(name, value);
    });
  });
});`

**Comment by CosmicWebServices** [comment]
Cool

**Comment by ghost** [comment]
Maybe we should use [gitter](http://gitter.im) instead of an issue?

**Comment by CosmicWebServices** [comment]
good Idea

**Comment by CosmicWebServices** [comment]
I am making it

**Comment by CosmicWebServices** [comment]
https://gitter.im/ilovecode1/bridgevar?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by CosmicWebServices** [comment]
Ignore sorry

**Comment by edward789121** [comment]
can i use this in my scratch mod?

**Comment by CosmicWebServices** [comment]
Sure just give us credit

**Comment by edward789121** [comment]
CWS said: sure just give us credit

ok do you know some code to use because it looks like it only works with scratch

**Comment by CosmicWebServices** [comment]
I am sorry I do not know what you mean

do you mean python

**Comment by edward789121** [comment]
Ya

**Comment by CosmicWebServices** [comment]
I think you are looking for something different then bridge variable try mesh variables
